version: 0.2
env:
  variables:
    APP_NAME: "portfolio-website"
phases:
  install:
    runtime-versions:
      nodejs: 12.14.1
    commands:
      - echo install process started
      - node -v
      - npm install
  build:
    commands:
      - echo build process started now
      - node_modules/.bin/ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://rahalkanishka.com --delete
